"""Add security_checked column

Revision ID: 290dbbad31df
Revises: 6a596287da0f
Create Date: 2025-03-11 08:03:06.453209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290dbbad31df'
down_revision = '6a596287da0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_checked', sa.Boolean(), nullable=True))
        batch_op.alter_column('ip',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('services',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('open_ports')
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('open_ports', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('services',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('ip',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('security_checked')

    # ### end Alembic commands ###
