"""Add device_devicetype to ScanHistory

Revision ID: 33f2a013fba5
Revises: 290dbbad31df
Create Date: 2025-03-11 09:23:20.862307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f2a013fba5'
down_revision = '290dbbad31df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('open_ports', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_column('open_ports')
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###
